In [1]:
import sys
path = '/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py'
sys.path.append(path)

In [2]:
from algo.cvb0 import CollapsedVB

---
Mock Test

In [3]:
documents = [
    ["apple", "orange", "banana", "apple"],
    ["orange", "banana", "apple", "fruit"],
    ["berry", "fruit", "apple", "banana"],
    ["apple", "berry", "orange", "fruit"]
]
K = 3
cvb = CollapsedVB(documents, K)
cvb.run(100)

theta_dk = cvb.get_topic_distributions()
phi_kv = cvb.get_word_distributions()

print("Topic distributions per document:", theta_dk)
print("Word distributions per topic:", phi_kv)

Iteration 0
Iteration 10
Iteration 20
Iteration 30
Iteration 40
Iteration 50
Iteration 60
Iteration 70
Iteration 80
Iteration 90
Topic distributions per document: [[0.25581395 0.72093023 0.02325581]
 [0.25581395 0.25581395 0.48837209]
 [0.48837209 0.48837209 0.02325581]
 [0.25581395 0.72093023 0.02325581]]
Word distributions per topic: [[0.01818182 0.2        0.2        0.38181818 0.2       ]
 [0.22105263 0.11578947 0.43157895 0.01052632 0.22105263]
 [0.44       0.44       0.04       0.04       0.04      ]]


/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py:83: RuntimeWarning: overflow encountered in exp
  gamma_dn[k] = np.exp(log_term_n_dk + correction_n_dk + log_term_n_kv + correction_n_kv + log_term_n_k + correction_n_k)
/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py:86: RuntimeWarning: invalid value encountered in divide
  gamma_dn /= np.sum(gamma_dn)


---
Real Data

In [4]:
import lda
import lda.datasets

In [5]:
X = lda.datasets.load_reuters()
vocab = lda.datasets.load_reuters_vocab()
titles = lda.datasets.load_reuters_titles()

In [8]:
titles

('0 UK: Prince Charles spearheads British royal revolution. LONDON 1996-08-20',
 '1 GERMANY: Historic Dresden church rising from WW2 ashes. DRESDEN, Germany 1996-08-21',
 "2 INDIA: Mother Teresa's condition said still unstable. CALCUTTA 1996-08-23",
 '3 UK: Palace warns British weekly over Charles pictures. LONDON 1996-08-25',
 '4 INDIA: Mother Teresa, slightly stronger, blesses nuns. CALCUTTA 1996-08-25',
 "5 INDIA: Mother Teresa's condition unchanged, thousands pray. CALCUTTA 1996-08-25",
 '6 INDIA: Mother Teresa shows signs of strength, blesses nuns. CALCUTTA 1996-08-26',
 "7 INDIA: Mother Teresa's condition improves, many pray. CALCUTTA, India 1996-08-25",
 '8 INDIA: Mother Teresa improves, nuns pray for "miracle". CALCUTTA 1996-08-26',
 '9 UK: Charles under fire over prospect of Queen Camilla. LONDON 1996-08-26',
 '10 UK: Britain tells Charles to forget Camilla. LONDON 1996-08-27',
 "11 COTE D'IVOIRE: FEATURE - Quiet homecoming for reprieved Ivory Coast maid. ABIDJAN 1996-08-28",


In [6]:
X

array([[1, 0, 1, ..., 0, 0, 0],
       [7, 0, 2, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [7]:
vocab

('church',
 'pope',
 'years',
 'people',
 'mother',
 'last',
 'told',
 'first',
 'world',
 'year',
 'president',
 'teresa',
 'charles',
 'catholic',
 'during',
 'life',
 'u.s',
 'city',
 'public',
 'time',
 'since',
 'family',
 'king',
 'former',
 'british',
 'harriman',
 'against',
 'country',
 'vatican',
 'made',
 'three',
 'hospital',
 'minister',
 'home',
 'died',
 'tuesday',
 'government',
 "n't",
 'million',
 'prince',
 'john',
 'very',
 'war',
 'say',
 'order',
 'day',
 'political',
 'leader',
 'heart',
 'roman',
 'yeltsin',
 'later',
 'france',
 'party',
 'monday',
 'death',
 'clinton',
 'sunday',
 'elvis',
 'state',
 'diana',
 'royal',
 'wednesday',
 'churchill',
 'official',
 'service',
 'including',
 'film',
 'while',
 'week',
 'left',
 'work',
 'paris',
 'around',
 'american',
 'saying',
 'take',
 'doctors',
 'group',
 'son',
 'queen',
 'house',
 'police',
 'national',
 'under',
 'surgery',
 'next',
 'peace',
 'paul',
 'long',
 'ceremony',
 'month',
 'thursday',
 'french',


In [9]:
def matrix_to_documents(doc_term_matrix, vocabulary):
    documents = []
    for row in doc_term_matrix:
        doc = []
        for term_index, term_count in enumerate(row):
            for _ in range(term_count):  # Add each term the number of times it appears
                doc.append(vocabulary[term_index])
        documents.append(doc)
    return documents

# Convert the document-term matrix to lists of words
converted_documents = matrix_to_documents(X, vocab)

# Now that we have the documents in the right format, we can apply the CollapsedVB class
K = 10  # You can choose the number of topics
cvb = CollapsedVB(converted_documents, K)
cvb.run(100)

theta_dk = cvb.get_topic_distributions()
phi_kv = cvb.get_word_distributions()

print("Topic distributions per document:", theta_dk)
print("Word distributions per topic:", phi_kv)


/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py:78: RuntimeWarning: divide by zero encountered in scalar divide
  correction_n_kv = -Var_n_kv / (2 * (self.beta + E_n_kv)**2)
/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py:83: RuntimeWarning: invalid value encountered in scalar add
  gamma_dn[k] = np.exp(log_term_n_dk + correction_n_dk + log_term_n_kv + correction_n_kv + log_term_n_k + correction_n_k)
/Users/wadimoughanim/Documents/education/Master_MVA/s2/bayesian/mva-bayesian/algo/cvb0.py:77: RuntimeWarning: divide by zero encountered in scalar divide
  correction_n_dk = -Var_n_dk / (2 * (self.alpha + E_n_dk)**2)


Iteration 0
